include: package:flutter_lints/flutter.yaml


analyzer:
  exclude: [ build/** ]
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    todo: ignore


linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    constant_identifier_names: false
    prefer_const_literals_to_create_immutables: false
    use_named_constants: true
    always_declare_return_types: true
    prefer_relative_imports: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    avoid_catching_errors: true
    avoid_empty_else: true
    empty_catches: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options